name: keyboard_actions_bar_example
description: Example app for keyboard_actions_bar.
publish_to: none
version: 1.0.2

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  keyboard_actions_bar:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
